/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.FlowLayout;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelDominio.Viagem;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import modelDominio.Condutor;
import modelDominio.Passageiro;
import modelDominio.StatusPassageiro;
import view.util.ComboboxMotorista;
import view.util.ComboboxPassageiro;
import java.sql.Timestamp;
import java.time.Instant;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;


/**
 *
 * @author murilocost4
 */
public class TelaCadViagens extends javax.swing.JFrame {
    ArrayList<Passageiro> listaPassageiros = new ArrayList<>();
    private int codigo = -1;
    /**
     * Creates new form TelaCadViagens
     */
    
    
    
    private void preencheComboboxMotoristas() {
        // preenchendo o comboBox dos Marcas
        ArrayList<Condutor> listaCondutor = new ArrayList<Condutor>();
        listaCondutor = Principal.ccont.getCondutorLista();
        ComboboxMotorista.preencheComboBoxMotorista(-1, jCBMotorista, listaCondutor);
    }
    
    private void preencheComboboxPassageiro() {
        ArrayList<Passageiro> listaPassageiro = new ArrayList<Passageiro>();
        listaPassageiro = Principal.ccont.getPassageiroLista();
        ComboboxPassageiro.preencheComboBoxPassageiro(-1, jCBPassageiro, listaPassageiro);
    }
    
    
    
    public TelaCadViagens() {
        initComponents();
        preencheComboboxMotoristas();
        preencheComboboxPassageiro();
        
    }
    
    public void setViagem(Viagem v){
            codigo = v.getTrip_id(); // salvando o código para usar depois no salvar
            jTFOrigem.setText(v.getOrigem());
            jTFDestino.setText(v.getDestino());
            jTFData.setText(v.getData());
            jTFRetorno.setText(v.getRetorno());
            jTFSaida.setText(v.getSaida());
            jCBStatus.setSelectedIndex(v.getStatus_viagem());
            jCBMotorista.setSelectedIndex(v.getCodCondutor());

            ArrayList<StatusPassageiro> spLista = (ArrayList<StatusPassageiro>) v.getStatusPassageiros();

            jPPassageiros.removeAll();

            // Configura o layout do painel como BoxLayout para alinhar os labels verticalmente
            jPPassageiros.setLayout(new BoxLayout(jPPassageiros, BoxLayout.Y_AXIS));

            // Adiciona um JLabel para cada passageiro na lista
            for (StatusPassageiro sp : spLista) {
                JLabel label = new JLabel(sp.getPassageiro().getNomeUsuario());
                label.setFont(new Font("Arial", Font.PLAIN, 16)); // Define o estilo do texto
                jPPassageiros.add(label); // Adiciona o JLabel ao painel
            }
            
            jPPassageiros.revalidate(); // Atualiza o layout do painel
            jPPassageiros.repaint(); 
    }
    
    



    
    /*private void adicionarPassageiro(Viagem viagem) {
        
        jPPassageiros.setLayout(new FlowLayout());
        
        listaPassageiros = new ArrayList<>();
        
        String passageiroSelecionado = (String) jCBPassageiro.getSelectedItem();
        if (jCBPassageiro != null && jCBPassageiro.getSelectedItem() != null) {
            int passageiroId = Integer.parseInt(passageiroSelecionado.split(" - ")[0]);
            String passageiroNome = passageiroSelecionado.split(" - ")[1];
            
            Timestamp horaAtualizacao = Timestamp.from(Instant.now());
            
            Passageiro p = new Passageiro(passageiroId);
            
            listaPassageiros.add(new StatusPassageiro(viagem,p,1, horaAtualizacao));
            
            JLabel passageiroLabel = new JLabel(passageiroNome);
            jPPassageiros.add(passageiroLabel);
            jPPassageiros.revalidate();
            jPPassageiros.repaint();
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFOrigem = new javax.swing.JTextField();
        jTFDestino = new javax.swing.JTextField();
        jTFData = new javax.swing.JTextField();
        jTFSaida = new javax.swing.JTextField();
        jTFRetorno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jCBMotorista = new javax.swing.JComboBox<>();
        jBCancelar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jCBStatus = new javax.swing.JComboBox<>();
        jCBPassageiro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jBAdicionarPassageiro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPPassageiros = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Viagens");

        jTFOrigem.setToolTipText("");

        jLabel2.setText("Origem");

        jLabel3.setText("Destino");

        jLabel4.setText("Data");

        jLabel5.setText("Motorista");

        jLabel6.setText("Saída");

        jLabel7.setText("Retorno");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jCBMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMotoristaActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jCBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Iniciado", "Iniciado", "Finalizado" }));

        jCBPassageiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Passageiros");

        jBAdicionarPassageiro.setText("Adicionar");
        jBAdicionarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarPassageiroActionPerformed(evt);
            }
        });

        jLabel9.setText("Status da Viagem");

        javax.swing.GroupLayout jPPassageirosLayout = new javax.swing.GroupLayout(jPPassageiros);
        jPPassageiros.setLayout(jPPassageirosLayout);
        jPPassageirosLayout.setHorizontalGroup(
            jPPassageirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPPassageirosLayout.setVerticalGroup(
            jPPassageirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTFSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFRetorno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jCBPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBAdicionarPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTFOrigem)
                                                        .addComponent(jTFDestino)
                                                        .addComponent(jCBMotorista, 0, 216, Short.MAX_VALUE))
                                                    .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPPassageiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jTFDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionarPassageiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancelar)
                    .addComponent(jBVoltar))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

        
        if (jTFOrigem.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo Origem");
            jTFOrigem.requestFocus();
        } else if (jTFDestino.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo Destino");
            jTFDestino.requestFocus();
        } else if (jTFData == null) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo Data");
            jTFData.requestFocus();
        } else if (jTFSaida == null) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo Saida");
            jTFSaida.requestFocus();
        } else if (jTFRetorno == null) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo Retorno");
            jTFRetorno.requestFocus();
        } else {
            
            Viagem v = new Viagem(jTFOrigem.getText(), jTFDestino.getText(), jTFData.getText(), jTFSaida.getText(), jTFRetorno.getText(), jCBStatus.getSelectedIndex(), jCBMotorista.getSelectedIndex());
            
            
            
            boolean ok = false;
            
            if (codigo == -1) {
                int idGerado = Principal.ccont.viagemInserir(v);
                System.out.println("Id Gerado:"+idGerado);
                if (idGerado != 0) {
                    ok = true;
                    ArrayList<StatusPassageiro> spLista = new ArrayList<>();
                    for (Passageiro p : listaPassageiros) {
                        Timestamp horaAtualizacao = Timestamp.from(Instant.now());
                        StatusPassageiro statusPassageiro = new StatusPassageiro(idGerado, p, 1, horaAtualizacao);
                        Principal.ccont.statusPassageiroInserir(statusPassageiro);
                        spLista.add(statusPassageiro);
                    }
                   v.setStatusPassageiros(spLista);
                   
                   Principal.ccont.viagemAlterar(v);
                }
                
            } else {
                v.setTrip_id(codigo);
                ArrayList<StatusPassageiro> spLista = new ArrayList<>();
                    for (Passageiro p : listaPassageiros) {
                        Timestamp horaAtualizacao = Timestamp.from(Instant.now());
                        StatusPassageiro statusPassageiro = new StatusPassageiro(codigo, p, 1, horaAtualizacao);
                        Principal.ccont.statusPassageiroInserir(statusPassageiro);
                        spLista.add(statusPassageiro);
                    }
                   v.setStatusPassageiros(spLista);
                ok = Principal.ccont.viagemAlterar(v);
                
                
            }
            
            if (!ok) {
                JOptionPane.showMessageDialog(this,
                    "Ocorreu um  erro",
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Viagem salva com sucesso",
                    this.getTitle(),
                    JOptionPane.INFORMATION_MESSAGE);
                jTFOrigem.requestFocus();
                jTFOrigem.setText("");
                jTFDestino.setText("");
                jTFData.setText("");
                jTFSaida.setText("");
                jTFRetorno.setText("");
            }
            this.dispose();
        }
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jCBMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBMotoristaActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBAdicionarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarPassageiroActionPerformed
        if (jCBPassageiro != null && jCBPassageiro.getSelectedItem() != null) {
        // Obtém o item selecionado do combo box
        ComboboxPassageiro passageiroSelecionado = (ComboboxPassageiro) jCBPassageiro.getSelectedItem();

        // Usa getKey() para obter o ID do passageiro
        int passageiroId = passageiroSelecionado.getKey();
        String passageiroNome = passageiroSelecionado.toString(); // toString retorna o nome


        Passageiro p = new Passageiro(passageiroId, passageiroNome);
        
        // Adiciona à lista local
        listaPassageiros.add(p);
        
        
        // Atualiza a interface
        
            JLabel label = new JLabel(p.getNomeUsuario());
            label.setFont(new Font("Arial", Font.PLAIN, 16));
            jPPassageiros.add(label);
        
    }

        /*if (jCBPassageiro != null && jCBPassageiro.getSelectedItem() != null) {
        // Obtém o item selecionado do combo box
        ComboboxPassageiro passageiroSelecionado = (ComboboxPassageiro) jCBPassageiro.getSelectedItem();

        // Usa getKey() para obter o ID do passageiro
        int passageiroId = passageiroSelecionado.getKey();
        String passageiroNome = passageiroSelecionado.toString(); // toString retorna o nome


        Passageiro p = new Passageiro(passageiroId, passageiroNome);
        
        // Adiciona à lista local
        listaPassageiros.add(p);
        
        
        // Atualiza a interface
        
            JLabel label = new JLabel(p.getNomeUsuario());
            label.setFont(new Font("Arial", Font.PLAIN, 16));
            jPPassageiros.add(label);
        
    }*/
    }//GEN-LAST:event_jBAdicionarPassageiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadViagens().setVisible(true);
            }
        });
    }

    void setModal(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarPassageiro;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCBMotorista;
    private javax.swing.JComboBox<String> jCBPassageiro;
    private javax.swing.JComboBox<String> jCBStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPPassageiros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFData;
    private javax.swing.JTextField jTFDestino;
    private javax.swing.JTextField jTFOrigem;
    private javax.swing.JTextField jTFRetorno;
    private javax.swing.JTextField jTFSaida;
    // End of variables declaration//GEN-END:variables
}
