/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelDominio.Admin;
import modelDominio.Condutor;
import modelDominio.Passageiro;
import modelDominio.Usuario;

/**
 *
 * @author murilocost4
 */
public class TelaCadUsuarios extends javax.swing.JFrame {
    
    private int codigo = -1;

    /**
     * Creates new form TelaCadUsuarios
     */
    public TelaCadUsuarios() {
        initComponents();
    }
    
    public void setUsuario (Usuario usr) {
        codigo = usr.getCodUsuario();
        jTFNome.setText(usr.getNomeUsuario());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFNome = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jTFNascimento = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jTFFone = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        jBSalvar = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFNome.setText("Nome");

        jTFEmail.setText("Email");

        jTFCpf.setText("CPF");

        jTFNascimento.setText("Nascimento");

        jTFEndereco.setText("Endereco");

        jTFFone.setText("Fone");

        jPFSenha.setText("Senha");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecionar>>", "Admin", "Condutor", "Passageiro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFNascimento))
                        .addComponent(jTFEmail)
                        .addComponent(jPFSenha)
                        .addComponent(jTFEndereco)
                        .addComponent(jTFFone)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalvar)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        if (jTFNome.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome");
        } else if (jCBTipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Tipo");
        } else if (jTFEmail.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Email");
        } else if (jPFSenha.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Senha");
        } else if (jTFCpf.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo CPF");
        } else if (jTFNascimento.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Nascimento");
        } else if (jTFEndereco.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Endereco");
        } else if (jTFFone.equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Fone");
        } else {
                        
            if (jCBTipo.getSelectedIndex() == 1) {
                Admin usr = new Admin(jTFNome.getText(), jTFCpf.getText(), jTFNascimento.getText(), jTFEndereco.getText(), jPFSenha.getText(), jTFEmail.getText(), jTFFone.getText());
                Boolean ok = Principal.ccont.usuarioInserir(usr);
                if (!ok) {
                    JOptionPane.showMessageDialog(this,
                        "Ocorreu um  erro",
                        this.getTitle(),
                        JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Usuario inserido com sucesso",
                        this.getTitle(),
                        JOptionPane.INFORMATION_MESSAGE);
                    jTFNome.requestFocus();
                    jTFNome.setText("");
                    jTFEmail.setText("");
                    jTFCpf.setText("");
                    jTFNascimento.setText("");
                    jTFEndereco.setText("");
                    jTFFone.setText("");
                    jPFSenha.setText("");
                    jCBTipo.setSelectedIndex(0);
                }
            } else if (jCBTipo.getSelectedIndex() == 2) {
                Condutor usr = new Condutor(jTFNome.getText(), jTFCpf.getText(), jTFNascimento.getText(), jTFEndereco.getText(), jPFSenha.getText(), jTFEmail.getText(), jTFFone.getText());
                Boolean ok = Principal.ccont.usuarioInserir(usr);
                if (!ok) {
                    JOptionPane.showMessageDialog(this,
                        "Ocorreu um  erro",
                        this.getTitle(),
                        JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Usuario inserido com sucesso",
                        this.getTitle(),
                        JOptionPane.INFORMATION_MESSAGE);
                    jTFNome.requestFocus();
                    jTFNome.setText("");
                    jTFEmail.setText("");
                    jTFCpf.setText("");
                    jTFNascimento.setText("");
                    jTFEndereco.setText("");
                    jTFFone.setText("");
                    jPFSenha.setText("");
                    jCBTipo.setSelectedIndex(0);
                }
            } else if (jCBTipo.getSelectedIndex() == 3) {
                Passageiro usr = new Passageiro(jTFNome.getText(), jTFCpf.getText(), jTFNascimento.getText(), jTFEndereco.getText(), jPFSenha.getText(), jTFEmail.getText(), jTFFone.getText());
                Boolean ok = Principal.ccont.usuarioInserir(usr);
                if (!ok) {
                    JOptionPane.showMessageDialog(this,
                        "Ocorreu um  erro",
                        this.getTitle(),
                        JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Usuario inserido com sucesso",
                        this.getTitle(),
                        JOptionPane.INFORMATION_MESSAGE);
                    jTFNome.requestFocus();
                    jTFNome.setText("");
                    jTFEmail.setText("");
                    jTFCpf.setText("");
                    jTFNascimento.setText("");
                    jTFEndereco.setText("");
                    jTFFone.setText("");
                    jPFSenha.setText("");
                    jCBTipo.setSelectedIndex(0);
                }
            }
            
            
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFNascimento;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
